const sidebars = {
  guidesSidebar: [
    {
      Guides: [
        'guides/getting-started',
        'guides/permissions',
        'guides/camera-controlling',
        'guides/taking-photos',
        'guides/recording-videos',
        'guides/manage-lenses',
        'guides/blur-and-tone-mode',
        'guides/utils',
      ],
      API: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    'contributing',
    'example-app',
  ],
};

module.exports = sidebars;
